### ISSUE TITLE
Connection has been closed by peer

### ISSUE THREAD

**Issue by mbouchenoire** [r2dbc/r2dbc-mssql#108]
Hello,

I'm using `r2dbc-mssql` trough `org.springframework.boot:2.2.0.RC1`. The exact version is `r2dbc-mssql-0.8.0.RC2`. I'm injecting Spring's `DatabaseClient` (autoconfigured, see below).

Only after performing the first SQL query (successfully), if I don't use a connection within the connection pool for 1 minute, the connection will "timeout" with a WARN message saying `Connection has been closed by peer` (from class `ReactorNettyClient`).
All SQL queries perform well if I try to use them before the connections close.

The only configuration I've got is this :

```yaml
spring:
    r2dbc:
      url: r2dbc:mssql://<ip>:<port>/<db>
      username: <username>
      password: <password>
```

SQL Server does not close the connections if I use the well known Spring Data JPA implementation.

Do you know why this would happen ?

Maxime.
